export const awsData = [
  {
    results: [
      {
        co2e: 96.18874199999999,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_af_south_1",
          uuid: "c41332a9-aac8-4268-a054-cbc26f4d8518",
          id: "cpu-provider_aws-region_af_south_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "ZA-CPT",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 96.18874199999999,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 83.95803000000001,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_east_1",
          uuid: "1791a24c-8f4a-413a-8ace-90bb5cda4fc5",
          id: "cpu-provider_aws-region_ap_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "HK-HKG",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 83.95803000000001,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 52.447872,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_northeast_1",
          uuid: "9342030a-32e7-4fa5-b9c3-2e990976cba6",
          id: "cpu-provider_aws-region_ap_northeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "JP-TYO",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 52.447872,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 51.825911999999995,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_northeast_2",
          uuid: "5f81ab53-ef68-4870-a9e4-d734ee41b8a2",
          id: "cpu-provider_aws-region_ap_northeast_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "KR-SEL",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 51.825911999999995,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 52.447872,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_northeast_3",
          uuid: "d5fee7db-4b82-4301-8d68-ae8392898e60",
          id: "cpu-provider_aws-region_ap_northeast_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "JP-OSA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 52.447872,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 73.385148,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_south_1",
          uuid: "cee96936-9911-4289-8c4c-5b7b4c8a7459",
          id: "cpu-provider_aws-region_ap_south_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IN-BOM",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 73.385148,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 42.341898,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_southeast_1",
          uuid: "5375b2e6-0667-4612-b5b1-427737f22418",
          id: "cpu-provider_aws-region_ap_southeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "SG-SIN",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 42.341898,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 81.884976,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ap_southeast_2",
          uuid: "2ee11d47-9bc5-4e45-a9b7-f3c7031b8a9a",
          id: "cpu-provider_aws-region_ap_southeast_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "AU-SYD",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 81.884976,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 13.474632,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_ca_central_1",
          uuid: "7c89ef83-05e1-42aa-95c6-75c510eb0628",
          id: "cpu-provider_aws-region_ca_central_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "CA-MTR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 13.474632,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 57.526482,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_cn_north_1",
          uuid: "c3218440-0190-4e43-a9b9-343111f93507",
          id: "cpu-provider_aws-region_cn_north_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "CN-BJS",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 57.526482,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 57.526482,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_cn_northwest_1",
          uuid: "53a58bc0-1668-4400-9fa1-da49a58dbdbd",
          id: "cpu-provider_aws-region_cn_northwest_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "CN-NX",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 57.526482,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 35.034306,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_central_1",
          uuid: "6e4e6063-941b-455e-b52a-3b1e59daf673",
          id: "cpu-provider_aws-region_eu_central_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "DE-FRA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 35.034306,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 0.829134,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_north_1",
          uuid: "16b4876e-643a-44e9-87df-a408bd30322d",
          id: "cpu-provider_aws-region_eu_north_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "SE-STO",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 0.829134,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 24.150882,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_south_1",
          uuid: "82f9d835-e003-4a84-bd8b-bfe562b00f58",
          id: "cpu-provider_aws-region_eu_south_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IT-MIL",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 24.150882,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 32.754078,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_west_1",
          uuid: "d350c900-54e8-4ed0-86ae-61ee4f545224",
          id: "cpu-provider_aws-region_eu_west_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IE-DUB",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 32.754078,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 23.632728,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_west_2",
          uuid: "f12e5d2b-0f27-47f5-a1df-2f5e33dad174",
          id: "cpu-provider_aws-region_eu_west_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "GB-LON",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 23.632728,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 5.390028,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_eu_west_3",
          uuid: "c9be5438-2a34-44d5-8037-caa0051fa446",
          id: "cpu-provider_aws-region_eu_west_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "FR-PAR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 5.390028,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 75.872988,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_me_south_1",
          uuid: "4232307b-4645-45e6-9dc7-04b4f6f6d5bd",
          id: "cpu-provider_aws-region_me_south_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "BH-AMH",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 75.872988,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 7.670255999999999,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_sa_east_1",
          uuid: "e2798a05-3d05-4840-83f7-d4497774e6bb",
          id: "cpu-provider_aws-region_sa_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "BR-SAO",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 7.670255999999999,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 43.093506,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_east_1",
          uuid: "e8fc4ce0-8013-48ea-a86c-c40f73bf1da9",
          id: "cpu-provider_aws-region_us_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-VA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 43.093506,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 45.626022000000006,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_east_2",
          uuid: "e4954e05-3eed-498f-91c2-b5eec15a5587",
          id: "cpu-provider_aws-region_us_east_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-OH",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 45.626022000000006,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 43.093506,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_gov_east_1",
          uuid: "b874c47e-674c-4a5d-a490-c597deb397bc",
          id: "cpu-provider_aws-region_us_gov_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 43.093506,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 36.36714,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_gov_west_1",
          uuid: "55f89ca9-6023-47d0-a5c6-09cea935be07",
          id: "cpu-provider_aws-region_us_gov_west_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 36.36714,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 36.36714,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_west_1",
          uuid: "8e1fdcb8-0f37-429a-a275-4933d1e9f161",
          id: "cpu-provider_aws-region_us_west_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-GIR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 36.36714,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 36.36714,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_aws-region_us_west_2",
          uuid: "2a8eb57c-1d11-4c0d-838a-c76629f6c12c",
          id: "cpu-provider_aws-region_us_west_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-OR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 36.36714,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
    ],
  },
];

export const azureData = [
  {
    results: [
      {
        co2e: 78.669618,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_central_india",
          uuid: "a42dd9e6-6e5e-4ca3-a845-4e3ac8d4dc54",
          id: "cpu-provider_azure-region_central_india",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IN-PNQ",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 78.669618,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 52.471962,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_central_us",
          uuid: "7c5b9752-36e3-4d8e-945f-7894b1793944",
          id: "cpu-provider_azure-region_central_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-IA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 52.471962,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 90.003306,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_east_asia",
          uuid: "90e98df9-190b-4570-bbfb-bc1674671289",
          id: "cpu-provider_azure-region_east_asia",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "HK-HKG",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 90.003306,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 46.196736,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_east_us",
          uuid: "2fa569d9-306a-473d-891a-3ede172e223b",
          id: "cpu-provider_azure-region_east_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-VA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 46.196736,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 46.196736,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_east_us_2",
          uuid: "173c7337-aaf6-4cf3-ab42-57d5eda0f78c",
          id: "cpu-provider_azure-region_east_us_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-VA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 46.196736,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 46.196736,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_east_us_3",
          uuid: "40226246-8e1d-4fb0-ad59-dbae3ce7a0ea",
          id: "cpu-provider_azure-region_east_us_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-GA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 46.196736,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 48.91146,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_north_central_us",
          uuid: "21d63c25-b69a-4405-840b-f79b213c8d31",
          id: "cpu-provider_azure-region_north_central_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-IL",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 48.91146,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 31.1637,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_north_europe",
          uuid: "60518249-79a0-4229-8b8d-75977e96c815",
          id: "cpu-provider_azure-region_north_europe",
          access_type: "public",
          source: "CCF",
          year: "2022",
          region: "IE",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 31.1637,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 44.03433,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_south_central_us",
          uuid: "f2251595-3666-4670-b49a-4ba33dd4b1f1",
          id: "cpu-provider_azure-region_south_central_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-TX",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 44.03433,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 78.669618,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_south_india",
          uuid: "3da509d5-271e-478e-9f3c-374fefc8735f",
          id: "cpu-provider_azure-region_south_india",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IN-MAA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 78.669618,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 45.390378,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_southeast_asia",
          uuid: "c6b725b3-fad0-4bcd-9036-daba2a224b1b",
          id: "cpu-provider_azure-region_southeast_asia",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "SG-SIN",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 45.390378,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 25.334358,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_uk_south",
          uuid: "25f3be97-c591-4093-b03e-6b9eb241ecf6",
          id: "cpu-provider_azure-region_uk_south",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "GB-LON",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 25.334358,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 25.334358,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_uk_west",
          uuid: "be353893-f270-43a3-9d0f-82b2a6c8b46c",
          id: "cpu-provider_azure-region_uk_west",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "GB-CDF",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 25.334358,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 38.985942,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_central_us",
          uuid: "af6c260e-ccd3-4ffe-8982-5771a16a7e87",
          id: "cpu-provider_azure-region_west_central_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-WY",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 38.985942,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 36.73506,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_europe",
          uuid: "77fbc573-ff1c-45d9-a28a-8c6f66191310",
          id: "cpu-provider_azure-region_west_europe",
          access_type: "public",
          source: "CCF",
          year: "2022",
          region: "NL",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 36.73506,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 78.669618,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_india",
          uuid: "72a940d8-29e6-43db-b7bc-eace54f57d58",
          id: "cpu-provider_azure-region_west_india",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IN-BOM",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 78.669618,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 38.985942,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_us",
          uuid: "2f2a04e4-c262-4ae8-b0ec-0923a396ec82",
          id: "cpu-provider_azure-region_west_us",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-CA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 38.985942,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 38.985942,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_us_2",
          uuid: "136ba232-0627-4862-b7dd-8ce86f3abab1",
          id: "cpu-provider_azure-region_west_us_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-WA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 38.985942,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 38.985942,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_azure-region_west_us_3",
          uuid: "e3232b6f-4364-48d8-a028-95b49aac8d90",
          id: "cpu-provider_azure-region_west_us_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-AZ",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 38.985942,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
    ],
  },
];

export const gcpData = [
  {
    results: [
      {
        co2e: 82.366776,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_east_1",
          uuid: "3493fa51-bd68-4e0c-b093-55c86ae0d086",
          id: "cpu-provider_gcp-region_asia_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "TW",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 82.366776,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 95.307924,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_east_2",
          uuid: "98548b98-486f-4211-875a-7141ddd38b3d",
          id: "cpu-provider_gcp-region_asia_east_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "HK-HKG",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 95.307924,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 79.778196,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_northeast_1",
          uuid: "3c174071-a124-40bc-b1e8-3e75312deeb0",
          id: "cpu-provider_gcp-region_asia_northeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "JP-TYO",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 79.778196,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 79.778196,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_northeast_2",
          uuid: "81f4f04b-7b12-49f2-8f62-0720afd11afd",
          id: "cpu-provider_gcp-region_asia_northeast_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "JP-OSA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 79.778196,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 82.214352,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_northeast_3",
          uuid: "41299af6-3af9-4c1e-a2c0-cc6138a00cd1",
          id: "cpu-provider_gcp-region_asia_northeast_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "KR-SEL",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 82.214352,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 110.07597,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_south_1",
          uuid: "caec7f71-7cf4-4261-9d12-0ebef1ba3652",
          id: "cpu-provider_gcp-region_asia_south_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "IN-BOM",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 110.07597,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 75.058746,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_southeast_1",
          uuid: "4f7fceef-a18e-43e5-86ed-5e640022960f",
          id: "cpu-provider_gcp-region_asia_southeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "SG-SIN",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 75.058746,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 117.535986,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_asia_southeast_2",
          uuid: "ac8bac46-5895-4553-b141-3497901580a1",
          id: "cpu-provider_gcp-region_asia_southeast_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "ID-JKT",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 117.535986,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 110.38038,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_australia_southeast_1",
          uuid: "994625a1-b77e-4bef-ba35-73f877472428",
          id: "cpu-provider_gcp-region_australia_southeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "AU-SYD",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 110.38038,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 27.557208000000003,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_north_1",
          uuid: "c67b4a8b-a4db-4f6c-9471-fb424d4e6ffe",
          id: "cpu-provider_gcp-region_europe_north_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "FI-HMN",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 27.557208000000003,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 29.84094,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_west_1",
          uuid: "8ea8ef09-eaf2-4255-8939-766d51fa4898",
          id: "cpu-provider_gcp-region_europe_west_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "BE-GHI",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 29.84094,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 39.127854,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_west_2",
          uuid: "7bf40335-e921-496b-9489-b97335014c26",
          id: "cpu-provider_gcp-region_europe_west_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "GB-LON",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 39.127854,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 48.567192,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_west_3",
          uuid: "17c56baa-49b9-4c65-b8d0-569e8d6bca8a",
          id: "cpu-provider_gcp-region_europe_west_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "DE-FRA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 48.567192,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 72.165756,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_west_4",
          uuid: "2e3724d8-1073-44d5-88a0-f5eec737c6ad",
          id: "cpu-provider_gcp-region_europe_west_4",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "NL-EEM",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 72.165756,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 4.41504,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_europe_west_6",
          uuid: "9c57629a-eee6-4d6a-a893-8fb23c662e2b",
          id: "cpu-provider_gcp-region_europe_west_6",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "CH-ZRH",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 4.41504,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 21.771666,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_northamerica_northeast_1",
          uuid: "c0096b44-6932-471e-ace5-8470cb2e1436",
          id: "cpu-provider_gcp-region_northamerica_northeast_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "CA-MTR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 21.771666,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 16.594944,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_southamerica_east_1",
          uuid: "c29a05b9-ce04-450c-becd-6aff7ff6e9df",
          id: "cpu-provider_gcp-region_southamerica_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "BR-SAO",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 16.594944,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 72.927,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_central_1",
          uuid: "c9d26938-a7bf-4980-945b-9002ec359f76",
          id: "cpu-provider_gcp-region_us_central_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-IA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 72.927,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 76.1244,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_east_1",
          uuid: "2bdb6120-30c7-4d93-ae32-a58a55d5377e",
          id: "cpu-provider_gcp-region_us_east_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-SC",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 76.1244,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 58.311378000000005,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_east_4",
          uuid: "523aa3b8-81d2-468b-bcf2-846f48d86266",
          id: "cpu-provider_gcp-region_us_east_4",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-VA",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 58.311378000000005,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 17.813022,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_west_1",
          uuid: "55659c89-b953-42c3-b6ae-9120f4a8e52f",
          id: "cpu-provider_gcp-region_us_west_1",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-OR",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 17.813022,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 37.75779,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_west_2",
          uuid: "49daebb0-198c-4a87-997d-d398ad2e228b",
          id: "cpu-provider_gcp-region_us_west_2",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-LAX",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 37.75779,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 85.411752,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_west_3",
          uuid: "9aefc29c-ad34-4c8f-a414-92b941d7847f",
          id: "cpu-provider_gcp-region_us_west_3",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-SLC",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 85.411752,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
      {
        co2e: 74.754336,
        co2e_unit: "kg",
        co2e_calculation_method: "ar4",
        co2e_calculation_origin: "source",
        emission_factor: {
          activity_id: "cpu-provider_gcp-region_us_west_4",
          uuid: "553af056-1ddb-4587-a849-a4b924f223e7",
          id: "cpu-provider_gcp-region_us_west_4",
          access_type: "public",
          source: "CCF",
          year: "2021",
          region: "US-LAS",
          category: "Cloud Computing - CPU",
          lca_activity: "use_phase",
          data_quality_flags: ["notable_methodological_variance"],
        },
        constituent_gases: {
          co2e_total: 74.754336,
          co2e_other: null,
          co2: null,
          ch4: null,
          n2o: null,
        },
      },
    ],
  },
];
